In [18]:
import numpy as np

In [85]:
a=np.array([2,3,4,5,6,7])
a

array([2, 3, 4, 5, 6, 7])

In [22]:
b=np.array([[10,11,13,14],[45,22,56,43],[6,5,1,8]])

In [23]:
print(b)

[[10 11 13 14]
 [45 22 56 43]
 [ 6  5  1  8]]


In [4]:
b[0][0]

10

In [9]:
b[:][2]

[6, 5, 1, 8]

In [24]:
b[1,-3:]

array([22, 56, 43])

In [25]:
b[:,-2]

array([13, 56,  1])

In [27]:
b[:,-2:-1]

array([[13],
       [56],
       [ 1]])

In [30]:
b[:][2]

array([6, 5, 1, 8])

In [66]:
b[:,1:-2]

array([[11],
       [22],
       [ 5]])

In [45]:
print(b)

[[10 11 13 14]
 [45 22 56 43]
 [ 6  5  1  8]]


In [60]:
b[1:3,3:4]

array([[43],
       [ 8]])

In [61]:
b[0:2,2:4]

array([[13, 14],
       [56, 43]])

In [67]:
b[1,2]=39398

In [74]:
b

array([[   10,    11,    13,    14],
       [   45,    22, 39398,    43],
       [    6,     5,     1,     8]])

In [69]:
#insertion

In [86]:
a=np.append(a,60)
a

array([ 2,  3,  4,  5,  6,  7, 60])

In [76]:
b=np.append(b,[[1,2,3,4,6]], axis=0)
b

array([[   10,    11,    13,    14],
       [   45,    22, 39398,    43],
       [    6,     5,     1,     8],
       [    1,     2,     3,     4],
       [    1,     2,     3,     4]])

In [78]:
b=np.append(b,[[1],[2],[3],[4],[5]], axis=1)
b

array([[   10,    11,    13,    14,     1],
       [   45,    22, 39398,    43,     2],
       [    6,     5,     1,     8,     3],
       [    1,     2,     3,     4,     4],
       [    1,     2,     3,     4,     5]])

In [88]:
del a

ValueError: cannot delete array elements

In [87]:
print(a)

[ 2  3  4  5  6  7 60]


In [93]:
b=np.delete(b,0,axis=0)

In [90]:
a*2

array([  4,   6,   8,  10,  12,  14, 120])

In [91]:
a +11

array([13, 14, 15, 16, 17, 18, 71])

In [94]:
b - 11

array([[   34,    11, 39387,    32,    -9],
       [   -5,    -6,   -10,    -3,    -8],
       [  -10,    -9,    -8,    -7,    -7],
       [  -10,    -9,    -8,    -7,    -6]])

In [96]:
b.reshape(10,2)

array([[   45,    22],
       [39398,    43],
       [    2,     6],
       [    5,     1],
       [    8,     3],
       [    1,     2],
       [    3,     4],
       [    4,     1],
       [    2,     3],
       [    4,     5]])

In [97]:
b

array([[   45,    22, 39398,    43,     2],
       [    6,     5,     1,     8,     3],
       [    1,     2,     3,     4,     4],
       [    1,     2,     3,     4,     5]])

In [98]:
b.astype(float)

array([[4.5000e+01, 2.2000e+01, 3.9398e+04, 4.3000e+01, 2.0000e+00],
       [6.0000e+00, 5.0000e+00, 1.0000e+00, 8.0000e+00, 3.0000e+00],
       [1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 4.0000e+00],
       [1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00]])

In [99]:
b.astype('uint16')

array([[   45,    22, 39398,    43,     2],
       [    6,     5,     1,     8,     3],
       [    1,     2,     3,     4,     4],
       [    1,     2,     3,     4,     5]], dtype=uint16)